CREATE DATABASE IF NOT EXISTS DB;

USE DB;

CREATE TABLE IF NOT EXISTS TASKS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    STATUS ENUM('TODO', 'IN_PROGRESS', 'DONE') DEFAULT 'TODO',
    UPLOADED_FILE_OF_COMPLETION BLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);